name: sandy-binder
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - serpentTools
  - notebook>=7.0,<8
  - jupyterlab>=4.0,<5
  - pip
  - pip:
      - sandy
